### ISSUE TITLE
ModuleNotFoundError: No module named 'promptwatch.unit_tests'

### ISSUE THREAD

**Issue by bmanturner** [blip-solutions/promptwatch-client#8]
```python
from promptwatch.unit_tests import UnitTest
```

results in 

```bash
Traceback (most recent call last):
  File "/Users/bfturner/dev/heavynl/promptwatch.py", line 1, in <module>
    from promptwatch.unit_tests import UnitTest
  File "/Users/bfturner/dev/heavynl/promptwatch.py", line 1, in <module>
    from promptwatch.unit_tests import UnitTest
ModuleNotFoundError: No module named 'promptwatch.unit_tests'; 'promptwatch' is not a package
```

**Comment by bmanturner** [comment]
Also, if you're gonna dig around in there, could you add an api_key arg to UnitTest that gets passed to client if it makes sense to do so?

**Comment by bmanturner** [comment]
My mistake. I named my scratch file `promptwatch.py`
